/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSendWakePushRouteImport } from './routes/api/public/send-wake-push'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendWakePushRoute = ApiPublicSendWakePushRouteImport.update({
  id: '/api/public/send-wake-push',
  path: '/api/public/send-wake-push',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/family': typeof FamilyRoute
  '/history': typeof HistoryRoute
  '/api/public/send-wake-push': typeof ApiPublicSendWakePushRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/family': typeof FamilyRoute
  '/history': typeof HistoryRoute
  '/api/public/send-wake-push': typeof ApiPublicSendWakePushRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/family': typeof FamilyRoute
  '/history': typeof HistoryRoute
  '/api/public/send-wake-push': typeof ApiPublicSendWakePushRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/family' | '/history' | '/api/public/send-wake-push'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/family' | '/history' | '/api/public/send-wake-push'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/family'
    | '/history'
    | '/api/public/send-wake-push'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FamilyRoute: typeof FamilyRoute
  HistoryRoute: typeof HistoryRoute
  ApiPublicSendWakePushRoute: typeof ApiPublicSendWakePushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-wake-push': {
      id: '/api/public/send-wake-push'
      path: '/api/public/send-wake-push'
      fullPath: '/api/public/send-wake-push'
      preLoaderRoute: typeof ApiPublicSendWakePushRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FamilyRoute: FamilyRoute,
  HistoryRoute: HistoryRoute,
  ApiPublicSendWakePushRoute: ApiPublicSendWakePushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
